// <auto-generated />
using BrainGame.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BrainGame.Db.Migrations
{
    [DbContext(typeof(BrainGameContext))]
    partial class BrainGameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BrainGame.Db.Entities.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BrainGame.Db.Entities.Quiz.Correct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Corrects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswer = "Собака"
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswer = "Их нет"
                        },
                        new
                        {
                            Id = 3,
                            CorrectAnswer = "Пингвин"
                        },
                        new
                        {
                            Id = 4,
                            CorrectAnswer = "Арахис"
                        },
                        new
                        {
                            Id = 5,
                            CorrectAnswer = "Мухоморы"
                        },
                        new
                        {
                            Id = 6,
                            CorrectAnswer = "Боровик"
                        });
                });

            modelBuilder.Entity("BrainGame.Db.Entities.Quiz.Questions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CorrectAnswerId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CorrectAnswerId");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answers = "Собака,Кошка,Хомяк",
                            CorrectAnswerId = 1,
                            Number = 1,
                            Question = "Кто гавкает?",
                            QuizId = 1
                        },
                        new
                        {
                            Id = 2,
                            Answers = "Лисички,Опята,Мухоморы",
                            CorrectAnswerId = 5,
                            Number = 1,
                            Question = "Какие грибы ядовитые?",
                            QuizId = 3
                        },
                        new
                        {
                            Id = 3,
                            Answers = "Орел,Пингвин,Ворон",
                            CorrectAnswerId = 3,
                            Number = 2,
                            Question = "Какая птица не умеет летать?",
                            QuizId = 1
                        },
                        new
                        {
                            Id = 4,
                            Answers = "Зеленые,Желтые,Их нет",
                            CorrectAnswerId = 2,
                            Number = 1,
                            Question = "Какого цвета листья у деревьев зимой?",
                            QuizId = 2
                        },
                        new
                        {
                            Id = 5,
                            Answers = "Арахис,Фисташки,Грецкие",
                            CorrectAnswerId = 4,
                            Number = 2,
                            Question = "Как называется земляной орех?",
                            QuizId = 2
                        },
                        new
                        {
                            Id = 6,
                            Answers = "Волнушка,Боровик,Лисичка",
                            CorrectAnswerId = 6,
                            Number = 2,
                            Question = "Как еще называют Белый гриб?",
                            QuizId = 3
                        });
                });

            modelBuilder.Entity("BrainGame.Db.Entities.Quiz.Quizzes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Point")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Animals",
                            Point = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Animals",
                            Point = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mushrooms",
                            Point = 0
                        });
                });

            modelBuilder.Entity("BrainGame.Db.Entities.Quiz.Questions", b =>
                {
                    b.HasOne("BrainGame.Db.Entities.Quiz.Correct", "Correct")
                        .WithMany()
                        .HasForeignKey("CorrectAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrainGame.Db.Entities.Quiz.Quizzes", "Quizzes")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Correct");

                    b.Navigation("Quizzes");
                });
#pragma warning restore 612, 618
        }
    }
}
